# Generated by Django 6.0 on 2025-12-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Bank Transfer', 'Bank Transfer'), ('Credit', 'Credit (Pay Later)')], default='Credit', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_note',
            field=models.TextField(blank=True, help_text='e.g. Cheque No: 123456 or UPI Transaction ID'),
        ),
    ]
